/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio1;

import javax.swing.JOptionPane;

/**
 *
 * @author RogMir
 */
public class Formulario extends javax.swing.JDialog {

    /**
     * Creates new form Formulario
     * @param parent
     * @param modal
     */
    Formulario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jPanelOcultar.setVisible(false);
    }

    Formulario() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        jPanelOcultar.setVisible(false);
    }

    // Atributos
    int cont=0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Evento = new javax.swing.ButtonGroup();
        jPanelContacto = new javax.swing.JPanel();
        etiContacto = new javax.swing.JLabel();
        etiNombre = new javax.swing.JLabel();
        etiTfn = new javax.swing.JLabel();
        etiApellidos = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        jTextApellidos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        etiReserva = new javax.swing.JLabel();
        etiFecha = new javax.swing.JLabel();
        etiEvento = new javax.swing.JLabel();
        rbBanquete = new javax.swing.JRadioButton();
        rbJornada = new javax.swing.JRadioButton();
        rbCongreso = new javax.swing.JRadioButton();
        jPanelOcultar = new javax.swing.JPanel();
        etiCongreso = new javax.swing.JLabel();
        etiJornadas = new javax.swing.JLabel();
        jTextJornadas = new javax.swing.JTextField();
        cbHabitaciones = new javax.swing.JCheckBox();
        etiCantidad = new javax.swing.JLabel();
        comboCantiddad = new javax.swing.JComboBox();
        etiAsistentes = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        etiCocina = new javax.swing.JLabel();
        comboCocina = new javax.swing.JComboBox();
        jSpinner3 = new javax.swing.JSpinner();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        btnReservar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelContacto.setToolTipText("Datos de Contacto");

        etiContacto.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        etiContacto.setText("Datos de Contacto");

        etiNombre.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        etiNombre.setText("Nombre");
        etiNombre.setToolTipText("Indica tu nombre (Obligatorio)");

        etiTfn.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        etiTfn.setText("Teléfono");
        etiTfn.setToolTipText("Introduce tu teléfono (Obligatorio)");

        etiApellidos.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        etiApellidos.setText("Apellidos");
        etiApellidos.setToolTipText("Introduce tus apellidos (Obligatorio)");

        jTextNombre.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jTextNombre.setToolTipText("Introduce tu nombre");

        jTextTelefono.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jTextTelefono.setToolTipText("Introduce tu teléfono");

        jTextApellidos.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jTextApellidos.setToolTipText("Introduce tus apellidos");

        javax.swing.GroupLayout jPanelContactoLayout = new javax.swing.GroupLayout(jPanelContacto);
        jPanelContacto.setLayout(jPanelContactoLayout);
        jPanelContactoLayout.setHorizontalGroup(
            jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContactoLayout.createSequentialGroup()
                        .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiNombre)
                            .addComponent(etiTfn))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jTextTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etiApellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContactoLayout.createSequentialGroup()
                        .addComponent(etiContacto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelContactoLayout.setVerticalGroup(
            jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactoLayout.createSequentialGroup()
                .addComponent(etiContacto)
                .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContactoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanelContactoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiNombre)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiApellidos)
                            .addComponent(jTextApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(etiTfn)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        jPanel2.setToolTipText("Datos de Reserva");

        etiReserva.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        etiReserva.setText("Datos de Reserva");
        etiReserva.setToolTipText("");

        etiFecha.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        etiFecha.setText("Fecha");
        etiFecha.setToolTipText("Indica fecha y hora de inicio");

        etiEvento.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        etiEvento.setText("Tipo de Evento");
        etiEvento.setToolTipText("Indica tipo de Evento");

        Evento.add(rbBanquete);
        rbBanquete.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        rbBanquete.setText("Banquete");
        rbBanquete.setToolTipText("Banquete");
        rbBanquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBanqueteActionPerformed(evt);
            }
        });

        Evento.add(rbJornada);
        rbJornada.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        rbJornada.setText("Jornada");
        rbJornada.setToolTipText("Jornada");
        rbJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJornadaActionPerformed(evt);
            }
        });

        Evento.add(rbCongreso);
        rbCongreso.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        rbCongreso.setText("Congreso");
        rbCongreso.setToolTipText("Congreso");
        rbCongreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCongresoActionPerformed(evt);
            }
        });

        jPanelOcultar.setToolTipText("Datos del Congreso");

        etiCongreso.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        etiCongreso.setText("Datos del Congreso");
        etiCongreso.setToolTipText("Datos de Congreso");

        etiJornadas.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        etiJornadas.setText("Jornadas");

        jTextJornadas.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jTextJornadas.setToolTipText("Indica nº jornadas de duración");

        cbHabitaciones.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cbHabitaciones.setText("¿Necesita Habitaciones?");
        cbHabitaciones.setToolTipText("Habitaciones necesarias");

        etiCantidad.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        etiCantidad.setText("Cantidad");
        etiCantidad.setToolTipText("");

        comboCantiddad.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        comboCantiddad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        comboCantiddad.setToolTipText("Nº Habitaciones");

        javax.swing.GroupLayout jPanelOcultarLayout = new javax.swing.GroupLayout(jPanelOcultar);
        jPanelOcultar.setLayout(jPanelOcultarLayout);
        jPanelOcultarLayout.setHorizontalGroup(
            jPanelOcultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOcultarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiJornadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOcultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOcultarLayout.createSequentialGroup()
                        .addComponent(etiCantidad)
                        .addGap(18, 18, 18)
                        .addComponent(comboCantiddad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOcultarLayout.createSequentialGroup()
                        .addComponent(jTextJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbHabitaciones))))
            .addGroup(jPanelOcultarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(etiCongreso))
        );
        jPanelOcultarLayout.setVerticalGroup(
            jPanelOcultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOcultarLayout.createSequentialGroup()
                .addComponent(etiCongreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOcultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiJornadas)
                    .addComponent(jTextJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHabitaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOcultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiCantidad)
                    .addComponent(comboCantiddad, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        etiAsistentes.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        etiAsistentes.setText("Asistentes");

        jSpinner2.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jSpinner2.setToolTipText("Nº Asistentes");

        etiCocina.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        etiCocina.setText("Tipo de cocina");
        etiCocina.setToolTipText("");

        comboCocina.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        comboCocina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buffet", "Carta", "Pedir cita al Chef", "No Precisa" }));
        comboCocina.setToolTipText("Indica tipo de cocina");

        jSpinner3.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jSpinner3.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1577833200000L), null, null, java.util.Calendar.DAY_OF_MONTH));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanelOcultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(etiFecha)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(107, 107, 107)
                                                .addComponent(etiEvento))
                                            .addComponent(etiReserva))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbCongreso)
                                            .addComponent(rbJornada)
                                            .addComponent(rbBanquete)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(etiAsistentes)
                                        .addGap(10, 10, 10)
                                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(etiCocina)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 12, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(etiReserva)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiFecha)
                            .addComponent(etiEvento)
                            .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbBanquete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbJornada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbCongreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelOcultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiAsistentes)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiCocina)
                    .addComponent(comboCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnReservar.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.setToolTipText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnReservar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
         this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rbBanqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBanqueteActionPerformed
        jPanelOcultar.setVisible(false);
    }//GEN-LAST:event_rbBanqueteActionPerformed

    private void rbJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJornadaActionPerformed
         jPanelOcultar.setVisible(false);
    }//GEN-LAST:event_rbJornadaActionPerformed

    private void rbCongresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCongresoActionPerformed
        jPanelOcultar.setVisible(true);
    }//GEN-LAST:event_rbCongresoActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        JOptionPane.showMessageDialog(null ,"Reserva realizada!!","Confirmación", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnReservarActionPerformed

// ************************************** Metodos de clase ************************************
    
    /**
     * Método en el que validamos que los campos no esten vacios.
     */
//    public void validar(){
//        
//        if(Campo1.getText().equals("")){validacion1.setVisible(true); cont++;} else {validacion1.setVisible(false);}
//        if(Campo2.getText().equals("")){validacion2.setVisible(true); cont++;} else {validacion2.setVisible(false);}
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Evento;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JCheckBox cbHabitaciones;
    private javax.swing.JComboBox comboCantiddad;
    private javax.swing.JComboBox comboCocina;
    private javax.swing.JLabel etiApellidos;
    private javax.swing.JLabel etiAsistentes;
    private javax.swing.JLabel etiCantidad;
    private javax.swing.JLabel etiCocina;
    private javax.swing.JLabel etiCongreso;
    private javax.swing.JLabel etiContacto;
    private javax.swing.JLabel etiEvento;
    private javax.swing.JLabel etiFecha;
    private javax.swing.JLabel etiJornadas;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JLabel etiReserva;
    private javax.swing.JLabel etiTfn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelContacto;
    private javax.swing.JPanel jPanelOcultar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextJornadas;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JRadioButton rbBanquete;
    private javax.swing.JRadioButton rbCongreso;
    private javax.swing.JRadioButton rbJornada;
    // End of variables declaration//GEN-END:variables
}
